/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Stars(props) {
  const { nodes, materials } = useGLTF('/login_env2.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Particles_Baked.geometry}
        material={materials.Utah}
        position={[0.76, -2.98, -0.75]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0}
      />
    </group>
  );
}

useGLTF.preload('/login_env2.gltf');
